// Generated by LiveScript 1.4.0
(function(){
  document.addEventListener('DOMContentLoaded', function(){
    console.log('domcontent loaded');
    return getFieldsFromExtension(['chrome_history_pages', 'chrome_history_visits'], function(data){
      console.log('got fields from extension');
      return console.log(data);
    });
  });
}).call(this);
